chain/urls.py
"""urls"""

from django.urls import path
from . import views

app_name = "blockchain"

urlpatterns = [
    path('', views.index, name="index"),
    path('transactions/index/', views.transactions_index, name="transactions_index"),
    path('transactions/next-block/', views.transactions_destined_for_next_block, name="transactions_destined_for_next_block"),
    path('transactions/anon-user/', views.transaction_anon, name="transaction_anon"),
    path('transactions/auth-user/', views.transaction_auth_user, name="transaction_auth_user"),
    path('block/detail/<str:index>/', views.block_detail, name="block_detail"),
    path('block/mine/', views.mine, name="mine"),
    path('nodes/index/', views.node_index, name="node_index"),
    path('nodes/register/', views.register_nodes, name="register_nodes"),
    path('nodes/resolve/', views.consensus, name="consensus"),
]

siteuser/api/urls.py
from django.urls import path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.CustomUserViewSet)
router.register(r'members', views.SiteUserViewSet)

user_api_urls = [
    path('users/', views.CustomUserViewSet.as_view({'get': 'list'}), name='customuser_api'),
    path('members/', views.SiteUserViewSet.as_view({'get': 'list'}), name='siteuser_api'),
]

siteuser/urls.py
"""urls live here"""

from django.urls import reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = "siteuser"

urlpatterns = [
    path("new/", views.new_siteuser, name="new"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("edit-profile/", views.SiteUserEdit.as_view(), name="edit_profile"),
    path('manage-account/', views.account_management, name='account_management'),
]

urlpatterns += [
    path('wallet/new/', views.generate_wallet, name="generate_wallet"),
    path('wallet/index/', views.wallet_index, name="wallet_index"),
    path('edit-alias/', views.edit_alias, name="edit_alias"),
]

urlpatterns += [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout-then-login/', auth_views.logout_then_login, name='logout_then_login'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('siteuser:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('siteuser:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('siteuser:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

siteuser/models.py
"""Models"""

from django.db import models
from django.urls import reverse
from django.conf import settings
# from django.contrib.auth.models import Group
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

from .utils import TimeStampedModel
from .utils import AutoSlugField

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("You must provide an email address")
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password=password)
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True, verbose_name='email address')
    is_active = models.BooleanField(default=False) # activate by email
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return "User - {}".format(self.email)

    def has_module_perms(self, app_label):
        return True

    def has_perm(self, perm, obj=None):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def prof(self):
        return self.siteuser.screen_name

class SiteUser(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = AutoSlugField(set_using="screen_name")
    screen_name = models.CharField(max_length=20, unique=True)

    class Meta:
        ordering = ['screen_name']
        verbose_name_plural = 'siteusers'

    def __str__(self):
        return self.screen_name

    def get_absolute_url(self):
        return reverse('siteuser:library', args=[str(self.id), str(self.slug)])

    def get_user_success_url(self):
        return reverse()

    def get_user_creation_url(self):
        return reverse('siteuser:new_activation', args=[str(self.user.id), str(self.screen_name)])

class Wallet(TimeStampedModel):
    alias = models.CharField(max_length=30)
    owner = models.ForeignKey(SiteUser, null=True, blank=True, on_delete=models.CASCADE)
    private_key = models.TextField()
    public_key = models.TextField()
    used = models.FloatField(default=0.00)
    balance = models.FloatField(default=0.00)

    def __str__(self):
        return self.owner.__str__() + " - " + self.alias

    def save(self, *args, **kwargs):
        return super(Wallet, self).save(*args, **kwargs)

siteuser/forms.py
"""Forms"""

from django import forms
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import SiteUser, Wallet

CustomUser = get_user_model()

class UserCreationForm(forms.ModelForm):
    """Custom UCF. Takes the standard
    variables of 'email', 'password1', 'password2'
    For creating instances of 'CustomUser'."""
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))

    class Meta:
        model = CustomUser
        fields = ('email', )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField

    class Meta:
        model = CustomUser
        fields = ["email", "password", "is_active", "is_admin"]

    def clean_password(self):
        return self.initial["password"]

class SiteUserMixin(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ("screen_name", )
        widgets = {
            "screen_name" : forms.TextInput(attrs={'class':'form-control', "placeholder" : "Display name"}),
        }

class SiteUserRegistrationForm(forms.Form):
    screen_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control', "placeholder" : "Screen name"}))

    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control', "placeholder" : "Email address"}))

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Enter password"}))

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Verify password"}))

    def clean(self):
        data = self.cleaned_data
        email = data.get("email", None).strip()
        password1 = data.get('password1', None).strip()
        password2 = data.get('password2', None).strip()
        screen_name = data.get("screen_name", None).strip()

        User = get_user_model()
        if User.objects.filter(email=email).exists():
            self.add_error('email', 'Email already registered.')

        if password1 and password2 and password1 != password2:
            self.add_error('password1', "Passwords do not match")

        if SiteUser.objects.filter(screen_name=screen_name).exists():
            self.add_error('screen_name', 'Display name already taken.')

class SiteUserEditForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ["screen_name",]

        widgets = {
            "screen_name" : forms.TextInput(attrs={'class' : 'form-control', "placeholder" : "Screen name"}),
        }

class PassWordGetterForm(forms.Form):
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Enter password"}))
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PassWordGetterForm, self).__init__(*args, **kwargs)

    def clean(self):
        password = self.cleaned_data['password']
        if check_password(password, self.user.password) is False:
            self.add_error('password', 'You entered a wrong password')

class EditAliasForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = ('alias', )

        widgets = {'alias' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Account identifier'})}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(EditAliasForm, self).__init__(*args, **kwargs)
        self.fields['account'].queryset = Wallet.objects.filter(owner__user=self.user)

    account = forms.ModelChoiceField(
        queryset=Wallet.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class' : 'form-control'}))

    def clean(self):
        alias = self.cleaned_data['alias']
        aliases = Wallet.objects.filter(owner__user=self.user).values_list('alias', flat=True)
        if alias in aliases:
            self.add_error('alias', "You already have a wallet name {}".format(alias))

siteuser/api/views.py
from rest_framework import viewsets
from ..models import CustomUser, SiteUser
from .import serializers

class SiteUserViewSet(viewsets.ModelViewSet):
    queryset = SiteUser.objects.all().order_by('created')
    serializer_class = serializers.SiteUserSerializer

class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = serializers.CustomUserSerializer

siteuser/views.py
"""Views"""

from django.db.models import Sum
from django.views import generic
from django.shortcuts import render, reverse, redirect
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from .models import SiteUser, Wallet
from chain.blockchain_client import Transaction, COINBASE, MINING_DIFFICULTY, MINING_REWARD, MINABLE_TRANSACTIONS

from .forms import PassWordGetterForm, SiteUserRegistrationForm, SiteUserEditForm, EditAliasForm
from django.contrib.auth.decorators import login_required

import binascii
import Crypto.Random
# from Crypto.Hash import SHA
from Crypto.PublicKey import RSA

CustomUser = get_user_model()

def new_siteuser(request):
    template = "siteuser/new.html"
    if request.method == 'POST':
        form = SiteUserRegistrationForm(request.POST)
        if form.is_valid():
            form = form.cleaned_data
            email = form['email']
            screen_name = form['screen_name']
            password1 = form['password1']

            user = CustomUser(email=email)
            user.set_password(password1)
            user.is_active=True
            user.save()

            new_user = SiteUser(user=user, screen_name=screen_name)
            new_user.save()
            login(request, user)
            return redirect('blockchain:index')
        else:
            return render(request, template, {'form' : form})
    return render(request, template, {'form' : SiteUserRegistrationForm()})

class SiteUserEdit(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = SiteUser
    form_class = SiteUserEditForm
    template_name = 'siteuser/edit.html'
    success_message = "Profile updated successfully."

    def get_object(self):
        user = self.request.user
        return SiteUser.objects.get(pk=user.pk)

    def get_success_url(self):
        return reverse('siteuser:account_management')

def delete_account(request):
    template = 'siteuser/delete_account.html'
    user = request.user
    siteuser = user.siteuser
    if request.method == 'POST':
        form = PassWordGetterForm(request.POST, user=user)
        if form.is_valid():
            siteuser.delete()
            user.delete()
            msg = "Your account has been permanently deleted"
            messages.success(request, msg)
            return redirect('/')
        else:
            # return render(request, template, {'form' : form })
            msg = "You entered a wrong password"
            messages.error(request, msg)
            return redirect('/')
    return render(request, template, {'form' : PassWordGetterForm(user=user) })

@login_required
def account_management(request):
    template = "siteuser/account_management.html"
    context = {}
    context['siteuser'] = request.user.siteuser
    return render(request, template, context)

def generate_wallet(request):
    """Generate a new wallet"""
    random_gen = Crypto.Random.new().read
    pr_key = RSA.generate(1024, random_gen)
    pub_key = pr_key.publickey()

    private_key = binascii.hexlify(pr_key.exportKey(format='DER')).decode('ascii')
    public_key = binascii.hexlify(pub_key.exportKey(format='DER')).decode('ascii')

    # get balance of coins in the system
    SUM_COINS = Wallet.objects.aggregate(total_balance=Sum('balance'))['total_balance']
    # If no wallet instance has been created, the balance returns None
    if SUM_COINS == None:
        SUM_COINS = 0.00
    if SUM_COINS < COINBASE:
        balance = 50.00
    else:
        balance = 0.00
    messages.success(request, "New wallet generated successfully and you have been assigned an initial coin balance of {}".format(balance))
    if request.user.is_authenticated is False:
        messages.error(request, "Copy your public and private keys and save them in a safe place at once as they cannot be recovered if lost")
        messages.success(request, "PUBLIC KEY: {}\n\nPRIVATE KEY: {}".format(public_key, private_key))
        return redirect('blockchain:index')
    else:
        messages.success(request, "You can view your account keys from your dashboard")
        # save credentials to database
        Wallet.objects.create(alias="Rename (30 characters)",
            owner=request.user.siteuser, private_key=private_key, balance=balance, public_key=public_key)
        return redirect('siteuser:account_management')

def edit_alias(request):
    user = request.user
    template = 'siteuser/wallet_edit_alias.html'

    if request.method == 'POST':
        form = EditAliasForm(request.POST, user=user)
        if form.is_valid():
            data = form.cleaned_data
            alias = data['alias']
            account = data['account']

            account.alias = alias
            account.save(update_fields=['alias'])
            messages.success(request, "Wallet alias updated successfully")
            return redirect('siteuser:account_management')
        else:
            return render(request, template, {'form' : form})
    return render(request, template, {'form' : EditAliasForm(user=user)})

def wallet_index(request):
    template = 'siteuser/wallet_index.html'
    context = {}
    context['wallets'] = Wallet.objects.all()
    return render(request, template, context)

siteuser/templates/siteuser/account_management.html
{% extends "voidcoin_base.html" %}
{% block title %}Manage your account{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Manage your account</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Users</a></li>
        <li class="breadcrumb-item active">Manage your account</li>
    </ol>
</nav>

<h2>About</h2>
<div class="container song-about">
    <div class="row">
        <div class="col-sm-6">
            <p class="text-secondary">Screen name: {{ siteuser.screen_name }}</p>
            <p class="text-secondary">Email: <a href="mailto:{{ siteuser.user.email }}">{{ siteuser.user.email }}</a></p>
            <p class="text-secondary">Member since: {{ siteuser.created }}</p>
            <p class="text-secondary">Last seen: {{ siteuser.user.last_login }}</p>
        </div>
        <div class="col-sm-6">
        </div>
    </div>
</div>

<hr>

<h2>Wallets</h2>

<div class="container">
    <div class="row text-center text-lg-left">
        {% for each in siteuser.wallet_set.all %}
            <a class="btn btn-sm btn-primary icon-buttons" href="" title="View keys" data-toggle="modal" data-target="#keyViewModal{{ each.pk }}">
                {{ each.alias }}
            </a>
            {% include 'siteuser/account_management_wallet_modal.html' %}
        {% endfor %}
    </div>
</div>

{% endblock content_content %}

siteuser/templates/siteuser/account_management_wallet_modal.html
<!--modal start-->
<div class="modal fade" id="keyViewModal{{ each.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="keyViewModalLabel"><span class="text-danger">{{ each.alias }}</span></h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p class="key-display"><b class="text-danger">Balance:</b> {{ each.balance }}</p>
                <p class="key-display"><b class="text-danger">Public key:</b> {{ each.public_key }}</p>
                <p class="key-display"><b class="text-danger">Private key:</b> {{ each.private_key }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>
<!--modal end-->

siteuser/templates/siteuser/delete_account.html
{% extends "voidcoin_base.html" %}
{% block title %}Delete account{% endblock %}

{% block body %}

    <h1 class='text-center'><a href="/" title='Return to homepage' style='text-decoration: none'>VoidCoin</a></h1>
    <hr>

    <div class="container register-forms">
        <h2 class='text-center'>Delete account</h2>
        <p class="text-danger">Are you really sure you want to delete your account? This process is irreversible.</p>
        <p class="text-secondary">Perhaps you might try temporary <a href="{% url 'siteuser:deactivate_account' %}">deactivation</a> it so that you can return to it later.</p>
        <p>Make sure to disconnect all your social media accounts before deleting</p>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <p>{{ form.password }}</p>
                <p>{{ form.password.errors }}</p>
            <button class="btn btn-primary btn-sm register-btn btn-danger" type="submit" value="Delete">Delete my account</button>
        </form>
    </div>
{% endblock body %}

siteuser/templates/siteuser/edit.html
{% extends "voidcoin_base.html" %}
{% block title %}Edit profile{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Edit profile</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Users</a></li>
        <li class="breadcrumb-item active">Edit profile</li>
    </ol>
</nav>


<div class="container upload-forms">
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Save">Save</button>
    </form>
</div>
{% endblock %}

siteuser/templates/siteuser/index.html
{% extends "voidcoin_base.html" %}
{% block title %}Users{% endblock title %}
{% load thumbnail %}
{% load static %}
{% load siteuser_tags %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Users</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">Members</li>
    </ol>
</nav>

<div class="container">
    <div class="row">
        {% for siteuser in siteuser_list %}
            <div class="col-lg-3 col-md-4 col-xs-6 col-sm-6 py-2 my-2 siteuser-index-details">
                {% thumbnail siteuser.avatar "150x150" crop="center" as im %}
                   <a href="{{ siteuser.avatar.url }}" target="_blank"><img alt="" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-fluid card"></a>
                {% empty %}
                   <img alt="" src="{% static 'img/django-logo.png' %}" width="150" height="150" class="img-fluid card">
                {% endthumbnail %}
                <p class="text-left"><a href="{% url 'siteuser:library' siteuser.pk siteuser.slug %}">{{ siteuser.screen_name }}</a></p>
                <p class="text-left">Roles:
                    {% for role in siteuser.roles.all %}
                        <a href="{% url 'siteuser:siteusers_common_roles' role %}" title='See all {{ role.name|title }}s ({{ role.siteuser_set.count }})'>{{ role.name|title }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="text-left">Location: <a href="{% url 'siteuser:siteusers_common_location' siteuser.location %}" title="See others in {{ siteuser.location }}">{{ siteuser.location }}</a></p>
                <p class="text-left">Activity: {{ siteuser.song_set.all|count_published }} songs, {{ siteuser.post_set.all|count_published }} blog posts,
                    {{ siteuser.score_set.count }} scores, {{ siteuser.midi_set.count }} midis, {{ siteuser.comment_set.count }} comments
                </p>
            </div>
        {% empty %}
            <p>No profiles added yet.</p>
        {% endfor %}
    </div>
</div>

{% endblock content_content %}

siteuser/templates/siteuser/key_view_modal.html
<!--modal start-->
<div class="modal fade" id="keyViewModal{{ each.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="keyViewModalLabel"><span class="text-danger">{{ each.alias }}</span> wallet</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p class="key-display"><b class="text-danger">Balance:</b> {{ each.balance }}</p>
                <p class="key-display"><b class="text-danger">Public key:</b> {{ each.public_key }}</p>
                <p class="key-display"><b class="text-danger">Private key:</b> {{ each.private_key }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
            </div>
        </div>
    </div>
</div>
<!--modal end-->

siteuser/templates/siteuser/new.html
{% extends "voidcoin_base.html" %}

{% block title %}Register{% endblock %}

{% block body %}

    <h1 class='text-center'><a href="/" title='Return to homepage' style='text-decoration: none'>VoidCoin</a></h1>
    <hr>

    <div class="container register-forms">
        <h2 class='text-center'>Sign Up</h2>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <p>{{ form.email }}</p>
                <p>{{ form.email.errors }}</p>
                <p>{{ form.screen_name }}</p>
                <p>{{ form.screen_name.errors }}</p>
                <p>{{ form.password1 }}</p>
                <p>{{ form.password1.errors }}</p>
                <p>{{ form.password2 }}</p>
                <p>{{ form.password2.errors }}</p>
            <button class="btn btn-primary btn-sm register-btn" type="submit" value="Sign Up">Sign Up</button>
        </form>
    </div>
{% endblock body %}

siteuser/templates/siteuser/wallet_edit_alias.html
{% extends "voidcoin_base.html" %}
{% block title %}Edit wallet alias{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}


<h1>Edit wallet alias</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Wallets</a></li>
        <li class="breadcrumb-item active">Edit wallet alias</li>
    </ol>
</nav>

<div class="container upload-forms">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Send">Send</button>
    </form>
</div>
{% endblock content_content %}

siteuser/templates/siteuser/wallet_index.html
{% extends "voidcoin_base.html" %}
{% block title %}Wallets{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Wallets</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">Wallets</li>
    </ol>
</nav>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Wallets</caption>
            <tr>
                <th>S/No.</th>
                <th>Alias</th>
                <th>Owner</th>
                <th>Address</th>
            </tr>
        </thead>
        <tbody>
        {% for wallet in wallets %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ wallet.alias }}</td>
                <td>{{ wallet.owner }}</td>
                <td>{{ wallet.public_key }}</td>
            </tr>
        {% empty %}
            <p>No wallet</p>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content_content %}