chain/urls.py
"""urls"""

from django.urls import path
from . import views

app_name = "blockchain"

urlpatterns = [
    path('', views.index, name="index"),
    path('transactions/index/', views.transactions_index, name="transactions_index"),
    path('transactions/next-block/', views.transactions_destined_for_next_block, name="transactions_destined_for_next_block"),
    path('transactions/anon-user/', views.transaction_anon, name="transaction_anon"),
    path('transactions/auth-user/', views.transaction_auth_user, name="transaction_auth_user"),
    path('block/detail/<str:index>/', views.block_detail, name="block_detail"),
    path('block/mine/', views.mine, name="mine"),
    path('nodes/index/', views.node_index, name="node_index"),
    path('nodes/register/', views.register_nodes, name="register_nodes"),
    path('nodes/resolve/', views.consensus, name="consensus"),
]

siteuser/urls.py
"""urls live here"""

from django.urls import reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = "siteuser"

urlpatterns = [
    path("new/", views.new_siteuser, name="new"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("edit-profile/", views.SiteUserEdit.as_view(), name="edit_profile"),
    path('manage-account/', views.account_management, name='account_management'),
]

urlpatterns += [
    path('wallet/new/', views.generate_wallet, name="generate_wallet"),
    path('wallet/index/', views.wallet_index, name="wallet_index"),
    path('edit-alias/', views.edit_alias, name="edit_alias"),
]

urlpatterns += [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout-then-login/', auth_views.logout_then_login, name='logout_then_login'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('siteuser:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('siteuser:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('siteuser:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

siteuser/forms.py
"""Forms"""

from django import forms
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import SiteUser, Wallet

CustomUser = get_user_model()

class UserCreationForm(forms.ModelForm):
    """Custom UCF. Takes the standard
    variables of 'email', 'password1', 'password2'
    For creating instances of 'CustomUser'."""
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))

    class Meta:
        model = CustomUser
        fields = ('email', )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField

    class Meta:
        model = CustomUser
        fields = ["email", "password", "is_active", "is_admin"]

    def clean_password(self):
        return self.initial["password"]

class SiteUserMixin(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ("screen_name", )
        widgets = {
            "screen_name" : forms.TextInput(attrs={'class':'form-control', "placeholder" : "Display name"}),
        }

class SiteUserRegistrationForm(forms.Form):
    screen_name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control', "placeholder" : "Screen name"}))

    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control', "placeholder" : "Email address"}))

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Enter password"}))

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Verify password"}))

    def clean(self):
        data = self.cleaned_data
        email = data.get("email", None).strip()
        password1 = data.get('password1', None).strip()
        password2 = data.get('password2', None).strip()
        screen_name = data.get("screen_name", None).strip()

        User = get_user_model()
        if User.objects.filter(email=email).exists():
            self.add_error('email', 'Email already registered.')

        if password1 and password2 and password1 != password2:
            self.add_error('password1', "Passwords do not match")

        if SiteUser.objects.filter(screen_name=screen_name).exists():
            self.add_error('screen_name', 'Display name already taken.')

class SiteUserEditForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        fields = ["screen_name",]

        widgets = {
            "screen_name" : forms.TextInput(attrs={'class' : 'form-control', "placeholder" : "Screen name"}),
        }

class PassWordGetterForm(forms.Form):
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', "placeholder" : "Enter password"}))
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PassWordGetterForm, self).__init__(*args, **kwargs)

    def clean(self):
        password = self.cleaned_data['password']
        if check_password(password, self.user.password) is False:
            self.add_error('password', 'You entered a wrong password')

class EditAliasForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = ('alias', )

        widgets = {'alias' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Account identifier'})}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(EditAliasForm, self).__init__(*args, **kwargs)
        self.fields['account'].queryset = Wallet.objects.filter(owner__user=self.user)

    account = forms.ModelChoiceField(
        queryset=Wallet.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class' : 'form-control'}))

    def clean(self):
        alias = self.cleaned_data['alias']
        aliases = Wallet.objects.filter(owner__user=self.user).values_list('alias', flat=True)
        if alias in aliases:
            self.add_error('alias', "You already have a wallet name {}".format(alias))

templates/blockchain_base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta content="text/html">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Blockchain | {% block title %}Happy choralling!{% endblock title %}</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Sunflower:300" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Inconsolata:700" rel="stylesheet">

		<!-- Algolia search javascript -->
		<script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>

		<script src="//cdn.jsdelivr.net/g/algoliasearch,algoliasearch.helper"></script>

		<!-- font awesome for icons -->
		<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

		<script src="//cdn.jsdelivr.net/hogan.js/3.0.2/hogan.min.js"></script>

		<!--midijs for playing midi-->
		<!-- <script type='text/javascript' src='//www.midijs.net/lib/midi.js'></script> -->

		{% comment %}[if lt IE 9] {% endcomment %}
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		{% comment %} [endif] {% endcomment %}

		{% load static %}
		<link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
		<link rel="stylesheet" href="{% static 'css/blockchain.css' %}">
		<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/blockchain.js' %}"></script>
		{{ form.media }}

		<!--google recaptcha-->
		<script src='https://www.google.com/recaptcha/api.js'></script>

	</head>

	{% block body %}
	<body>
		{% block navigation %}
		<nav class="navbar fixed-top navbar-expand-lg">
			<a class="navbar-brand" href="{% url 'blockchain:index' %}">
				<h3 style="color:blanchedalmond" title="https://www.blockchain.net/">BlockChain</h3>
			</a>

			<button type="button" class="navbar-toggler my-toggler" data-toggle="collapse" data-target=".navcontent">
				<span class="sr-only">Toggle navigation</span>
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse navcontent">
				<ul class="nav navbar-nav lefthand-navigation">
					<li class="nav-item"><a class="nav-link" href="/" title="Home">Home</a></li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Wallet</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'blockchain:generate_wallet' %}">New</a>
						    <a class="dropdown-item" href="{% url 'blockchain:wallet_detail' %}">View</a>
						</div>
					</li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Transactions</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'blockchain:transactions_index' %}">Index</a>
						    <a class="dropdown-item" href="{% url 'blockchain:initiate_transaction' %}">Initiate</a>
						    <a class="dropdown-item" href="{% url 'blockchain:make_transaction' %}">Make</a>
						</div>
					</li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Nodes</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'blockchain:node_index' %}">Index</a>
						    <a class="dropdown-item" href="{% url 'blockchain:register_nodes' %}">Configure</a>
						</div>
					</li>
				</ul>

				<ul class="navbar-nav ml-auto righthand-navigation">
					{% if user.is_authenticated %}

						<li class="nav-item dropdown">
						    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">New</a>
							<div class="dropdown-menu">
							    <a class="dropdown-item" href="">Hold</a>
							</div>
						</li>

						<li class="nav-item dropdown">
						    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog"></i></a>
						    <div class="dropdown-menu">
						        <a class="dropdown-item" href="{% url 'siteuser:account_management' %}">My account</a>
						        <a class="dropdown-item" href="{% url 'siteuser:edit_profile' %}">Edit profile</a>
							    <a class="dropdown-item" href="{% url 'siteuser:password_change' %}">Change password</a>
							    <a class="dropdown-item" href="{% url 'siteuser:password_reset' %}">Reset password</a>
							    <div class="dropdown-divider"></div>
							    <a class="dropdown-item" href="{% url 'siteuser:logout' %}">Logout</a>
							</div>
						</li>

						{% if user.is_admin %}
						<li class="nav-item dropdown">
						    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" href="/admin/">Django admin</a>
							    <div class="dropdown-divider"></div>
							</div>
						</li>
						{% endif %}
					{% else %}
						<li class="nav-item login-logout"><a class="btn btn-info btn-sm upload-button" href="{% url 'siteuser:login' %}">Log In</a></li>
						<li class="nav-item login-logout"><a class="btn btn-primary btn-sm upload-button" href="{% url 'siteuser:new' %}">Sign Up</a></li>
					{% endif %}

				</ul>
			</div>
		</nav>
		{% endblock navigation %}

		<div class="container-fluid">
		    {% include 'messages.html' %}
			<div class="row">
				<div class="col-sm-3 leftsidebar">
					{% block left_sidebar %}
					{% endblock left_sidebar %}
				</div>

				<div class="col-sm-6 centerspread" role='main'>

					{% block content_content %}
					    content-block
					{% endblock content_content %}

					{% if is_paginated %}
						{% include "pure_pagination.html" %}
					{% endif %}
				</div>

				<div class="col-sm-3 rightsidebar">
					{% block right_sidebar %}
					{% endblock right_sidebar %}
				</div>
			</div>
		</div>

		{% block footer %}
			{% include "footer.html" %}
		{% endblock footer %}

		{% endblock body %}

		<script type="text/javascript" >
			// add attributes to form input elements
			$(document).ready(function(){
				$("#id_username").attr('placeholder', '{{ form.username.label }}');
				$("#id_username").attr('class', 'form-control');

				$("#id_password").attr('placeholder', '{{ form.password.label }}');
				$("#id_password").attr('class', 'form-control');

				$("#id_email").attr('class', 'form-control');
				$("#id_email").attr('placeholder', '{{ form.email.label }}');

				$("#id_old_password").attr('class', 'form-control');
				$("#id_old_password").attr('placeholder', '{{ form.old_password.label }}');
				$("#id_new_password1").attr('class', 'form-control');
				$("#id_new_password1").attr('placeholder', '{{ form.new_password1.label }}');
				$("#id_new_password2").attr('class', 'form-control');
				$("#id_new_password2").attr('placeholder', '{{ form.new_password2.label }}');

				$("#id_password1").attr('class', 'form-control');
				// $("#id_password1").attr('placeholder', '{{ form.password1.label }}');
				$("#id_password2").attr('class', 'form-control');
				// $("#id_password2").attr('placeholder', '{{ form.password2.label }}');
			});
		</script>

		<script>
			// Initialize tooltip component
			$(function () {
				$('[data-toggle="tooltip"]').tooltip()
			})
            // Initialize popover component
			$(function () {
				$('[data-toggle="popover"]').popover()
			})
		</script>
	</body>
</html>

templates/messages.html
{% block messages %}
{% if messages %}
    {% for message in messages %}
      <div class="row alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p class="message-paragraph">{{ message }}</p>
      </div>
    {% endfor %}
{% endif %}
{% endblock messages %}

templates/pure_pagination.html
{% load i18n %}
{% block pure_pagination %}

<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "prev" %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

{% endblock pure_pagination %}

templates/readme.html
{% extends "voidcoin_base.html" %}
{% block title %}Home{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% load tags_and_filters %}
{% block content_content %}
<h1>VoidCoin</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
    </ol>
</nav>

<h2>README</h2>

{{ text|markdown_format }}



{% endblock content_content %}

templates/voidcoin_base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta content="text/html">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>VoidCoin | {% block title %}Best coin money cannot buy{% endblock title %}</title>

		<!--
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
		-->

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/superhero/bootstrap.min.css">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

		<!-- font awesome for icons -->
		<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

		{% comment %}[if lt IE 9] {% endcomment %}
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		{% comment %} [endif] {% endcomment %}

		{% load static %}
		<link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
		<link rel="stylesheet" href="{% static 'css/voidcoin.css' %}">
		<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/voidcoin.js' %}"></script>
		{{ form.media }}

		<!--google recaptcha-->
		<script src='https://www.google.com/recaptcha/api.js'></script>

	</head>

	{% block body %}
	<body>
		{% block navigation %}
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
			<a class="navbar-brand" href="{% url 'blockchain:index' %}">VoidCoin</a>

			<button type="button" class="navbar-toggler my-toggler" data-toggle="collapse" data-target=".navcontent">
				<span class="sr-only">Toggle navigation</span>
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse navcontent">
				<ul class="nav navbar-nav lefthand-navigation">
					<li class="nav-item"><a class="nav-link" href="/" title="Home">Home</a></li>
					<li class="nav-item"><a class="nav-link" href="/getting-started" title="Home">README</a></li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Wallet</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'siteuser:generate_wallet' %}">New</a>
						    <a class="dropdown-item" href="{% url 'siteuser:wallet_index' %}">Index</a>
						</div>
					</li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Transactions</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'blockchain:transactions_index' %}">Index</a>
						    <a class="dropdown-item" href="{% url 'blockchain:transactions_destined_for_next_block' %}">Next block</a>
						    <a class="dropdown-item" href="{% url 'blockchain:transaction_anon' %}">Initiate (json response)</a>
						    {% if user.is_authenticated %}
						        <a class="dropdown-item" href="{% url 'blockchain:transaction_auth_user' %}">Initiate</a>
						    {% endif %}
						</div>
					</li>
					<li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Nodes</a>
						<div class="dropdown-menu">
						    <a class="dropdown-item" href="{% url 'blockchain:node_index' %}">Index</a>
						    <a class="dropdown-item" href="{% url 'blockchain:register_nodes' %}">Configure</a>
						</div>
					</li>
				</ul>

				<ul class="navbar-nav ml-auto righthand-navigation">
					{% if user.is_authenticated %}
						<li class="nav-item dropdown">
						    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.siteuser }}</a>
						    <div class="dropdown-menu">
						        <a class="dropdown-item" href="{% url 'blockchain:mine' %}">Mine</a>
						        <div class="dropdown-divider"></div>
						        <a class="dropdown-item" href="{% url 'siteuser:account_management' %}">My Account</a>
						        <div class="dropdown-divider"></div>
						        <a class="dropdown-item" href="{% url 'siteuser:edit_profile' %}">Edit Profile</a>
						        <a class="dropdown-item" href="{% url 'siteuser:edit_alias' %}">Edit Wallet Alias</a>
						        <div class="dropdown-divider"></div>
							    <a class="dropdown-item" href="{% url 'siteuser:password_change' %}">Change Password</a>
							    <a class="dropdown-item" href="{% url 'siteuser:password_reset' %}">Reset Password</a>
							    <div class="dropdown-divider"></div>
							    <a class="dropdown-item" href="{% url 'siteuser:logout' %}">Logout</a>
							</div>
						</li>

						{% if user.is_admin %}
						<li class="nav-item dropdown">
						    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" href="/admin/">Django admin</a>
							</div>
						</li>
						{% endif %}
					{% else %}
						<li class="nav-item login-logout"><a class="btn btn-info btn-sm upload-button" href="{% url 'siteuser:login' %}">Log In</a></li>
						<li class="nav-item login-logout"><a class="btn btn-primary btn-sm upload-button" href="{% url 'siteuser:new' %}">Sign Up</a></li>
					{% endif %}

				</ul>
			</div>
		</nav>
		{% endblock navigation %}

		<div class="container-fluid">
		    {% include 'messages.html' %}
			<div class="row">
				<div class="col-sm-3 leftsidebar">
					{% block left_sidebar %}
					{% endblock left_sidebar %}
				</div>

				<div class="col-sm-6 centerspread" role='main'>

					{% block content_content %}
					    content-block
					{% endblock content_content %}

					{% if is_paginated %}
						{% include "pure_pagination.html" %}
					{% endif %}
				</div>

				<div class="col-sm-3 rightsidebar">
					{% block right_sidebar %}
					{% endblock right_sidebar %}
				</div>
			</div>
		</div>

		{% endblock body %}

		<script type="text/javascript" >
			// add attributes to form input elements
			$(document).ready(function(){
				$("#id_username").attr('placeholder', '{{ form.username.label }}');
				$("#id_username").attr('class', 'form-control');

				$("#id_password").attr('placeholder', '{{ form.password.label }}');
				$("#id_password").attr('class', 'form-control');

				$("#id_email").attr('class', 'form-control');
				$("#id_email").attr('placeholder', '{{ form.email.label }}');

				$("#id_old_password").attr('class', 'form-control');
				$("#id_old_password").attr('placeholder', '{{ form.old_password.label }}');
				$("#id_new_password1").attr('class', 'form-control');
				$("#id_new_password1").attr('placeholder', '{{ form.new_password1.label }}');
				$("#id_new_password2").attr('class', 'form-control');
				$("#id_new_password2").attr('placeholder', '{{ form.new_password2.label }}');

				$("#id_password1").attr('class', 'form-control');
				// $("#id_password1").attr('placeholder', '{{ form.password1.label }}');
				$("#id_password2").attr('class', 'form-control');
				// $("#id_password2").attr('placeholder', '{{ form.password2.label }}');
			});
		</script>

		<script>
			// Initialize tooltip component
			$(function () {
				$('[data-toggle="tooltip"]').tooltip()
			})
            // Initialize popover component
			$(function () {
				$('[data-toggle="popover"]').popover()
			})
		</script>
	</body>
</html>