chain/urls.py
"""urls"""

from django.urls import path
from . import views

app_name = "blockchain"

urlpatterns = [
    path('', views.index, name="index"),
    path('transactions/index/', views.transactions_index, name="transactions_index"),
    path('transactions/next-block/', views.transactions_destined_for_next_block, name="transactions_destined_for_next_block"),
    path('transactions/anon-user/', views.transaction_anon, name="transaction_anon"),
    path('transactions/auth-user/', views.transaction_auth_user, name="transaction_auth_user"),
    path('block/detail/<str:index>/', views.block_detail, name="block_detail"),
    path('block/mine/', views.mine, name="mine"),
    path('nodes/index/', views.node_index, name="node_index"),
    path('nodes/register/', views.register_nodes, name="register_nodes"),
    path('nodes/resolve/', views.consensus, name="consensus"),
]

chain/models.py
from django.db import models

chain/utils/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .fields import AutoCreatedField, AutoLastModifiedField

class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created = AutoCreatedField(_('created'))
    modified = AutoLastModifiedField(_('modified'))

    class Meta:
        abstract = True

chain/forms.py
from django import forms
from siteuser.models import Wallet

class AcceptTransactionForm(forms.Form):
    sender_address = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    recipient_address = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    signature = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    amount_to_receive = forms.FloatField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'step': 0.25}))

class NodeRegistrationForm(forms.Form):
    node_urls = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Comma-separated list e.g http://127.0.0.1:5000'}))

class InitiateTransactionForm(forms.Form):
    sender_address = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Sender address'}))
    sender_private_key = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Sender private key'}))
    recipient_address = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Recipient address'}))
    amount_to_send = forms.FloatField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'step': 0.25, 'placeholder' : 'Amount to send: steps of 0.25'}))

class InitiateTransactionAuthUserForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(InitiateTransactionAuthUserForm, self).__init__(*args, **kwargs)
        self.fields['wallet'].queryset = Wallet.objects.filter(owner__user=user)

    def clean(self):
        data = self.cleaned_data
        wallet = data['wallet']
        recipient = data['recipient']
        amount_to_send = data['amount_to_send']
        if wallet == recipient:
            self.add_error('recipient', 'Wallet cannot transfer to itself')
        if wallet.balance < amount_to_send:
            self.add_error('wallet', 'Low wallet balance: {}'.format(wallet.balance))

    wallet = forms.ModelChoiceField(
        queryset=Wallet.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class' : 'form-control'}))
    recipient = forms.ModelChoiceField(
        queryset=Wallet.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class' : 'form-control'}))
    amount_to_send = forms.FloatField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'step': 0.25}))

chain/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.http import  JsonResponse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import binascii
import Crypto.Random
# from Crypto.Hash import SHA
from Crypto.PublicKey import RSA

from siteuser.models import Wallet

from .blockchain_client import Transaction, COINBASE, MINING_DIFFICULTY, MINING_REWARD, MINABLE_TRANSACTIONS
from .forms import NodeRegistrationForm, InitiateTransactionForm, InitiateTransactionAuthUserForm

# Instantiate a blockchain
BLOCKCHAIN = settings.BLOCKCHAIN

def index(request):
    # get balance of coins in the system
    SUM_COINS = Wallet.objects.aggregate(total_balance=Sum('balance'))['total_balance']
    # If no wallet instance has been created, the balance returns None
    if SUM_COINS == None:
        SUM_COINS = 0.00
    template = 'chain/index.html'
    context = {}
    context['pending_transactions'] = BLOCKCHAIN.transactions
    context['chain'] = BLOCKCHAIN.chain
    context['mining_difficulty'] = MINING_DIFFICULTY
    context['mining_reward'] = MINING_REWARD
    context['coin_base'] = COINBASE
    context['unassigned'] = COINBASE - SUM_COINS
    context['mineable'] = MINABLE_TRANSACTIONS
    return render(request, template, context)

def transactions_index(request):
    """View all transactions on the blockchain"""
    template = 'chain/transactions_index.html'
    context = {}
    context['transactions'] = [transaction for block in BLOCKCHAIN.chain for transaction in block['transactions']]
    return render(request, template, context)

def transactions_destined_for_next_block(request):
    """View all transactions to be added to the next block"""
    template = 'chain/transactions_destined_for_next_block.html'
    context = {}
    context['transactions'] = BLOCKCHAIN.transactions
    return render(request, template, context)

@login_required
def transaction_auth_user(request):
    """
    Initiate a transaction and send it to a blockchain node
    """
    user = request.user
    template = 'chain/initiate_transaction.html'

    if request.method == 'POST':
        form = InitiateTransactionAuthUserForm(request.POST, user=user)
        if form.is_valid():
            data = form.cleaned_data
            wallet = data['wallet']
            recipient = data['recipient']
            amount_to_send = data['amount_to_send']

            sender_address = wallet.public_key
            sender_private_key = wallet.private_key
            recipient_address = recipient.public_key

            transaction_object = Transaction(sender_address, sender_private_key, recipient_address, amount_to_send)
            transaction = transaction_object.to_dict()
            signature = transaction_object.sign_transaction()
            verify = BLOCKCHAIN.verify_transaction_signature(sender_address, signature, transaction)
            if verify:
                BLOCKCHAIN.add_transaction_to_current_array(sender_address, recipient_address, amount_to_send, signature)
                messages.success(request, "Transaction signature verified successfully and transaction stacked for 'blocking'.")
            else:
                messages.error(request, "Transaction rejected")

            # update wallet balances
            wallet.balance -= amount_to_send
            wallet.save()
            recipient.balance += amount_to_send
            recipient.save()

            return redirect('blockchain:transactions_destined_for_next_block')
        else:
            return render(request, template, {'form' : form})
    return render(request, template, {'form' : InitiateTransactionAuthUserForm(user=user)})

@login_required
def transaction_anon(request):
    """
    Initiate a transaction and send it to a blockchain node
    """
    template = 'chain/initiate_transaction.html'
    context = {}

    if request.method == 'POST':
        form = InitiateTransactionForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            sender_address = data['sender_address']
            sender_private_key = data['sender_private_key']
            recipient_address = data['recipient_address']
            amount_to_send = data['amount_to_send']

            transaction_object = Transaction(sender_address, sender_private_key, recipient_address, amount_to_send)
            context['transaction'] = transaction_object.to_dict()
            context['signature'] = transaction_object.sign_transaction()
            return JsonResponse(context, status=201)
        else:
            return render(request, template, {'form' : form})
    return render(request, template, {'form' : InitiateTransactionForm()})

def block_detail(request, index):
    """View transactions in a block"""
    template = 'chain/block_detail.html'
    context = {}
    number = int(index)-1
    context['number'] = number + 1
    context['block_items'] = BLOCKCHAIN.chain[number]
    return render(request, template, context)

def mine(request):
    if BLOCKCHAIN.mineable() is False:
        messages.error(request, "At least {} transactions are needed to forge a block.".format(MINABLE_TRANSACTIONS))
        return redirect('blockchain:index')

    # get next proof from POW algorithm
    last_block = BLOCKCHAIN.last_block()
    nonce = BLOCKCHAIN.proof_of_work()

    # reward for finding proof
    BLOCKCHAIN.reward_miner(BLOCKCHAIN.node_id)

    # forge new block and add to chain
    previous_hash = BLOCKCHAIN.hash(last_block)
    BLOCKCHAIN.forge_block_and_add_to_chain(nonce, previous_hash)
    messages.success(request, "Block mined successfully. You have been rewarded with 0.25 coins")
    return redirect('blockchain:index')

def register_nodes(request):
    """Register new nodes"""
    template = 'chain/node_register.html'

    if request.method == 'POST':
        form = NodeRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            node_urls = data['node_urls'].split(',')

            for node_url in node_urls:
                try:
                    BLOCKCHAIN.register_node(node_url)
                    continue
                except ValueError:
                    messages.error(request, "Invalid node url: {}".format(node_url))
                    return redirect('blockchain:node_index')
            messages.success(request, "Node urls added successfully")
            return redirect('blockchain:node_index')
        else:
            return render(request, template, {'form' : form})
    return render(request, template, {'form' : NodeRegistrationForm()})

def node_index(request):
    template = 'chain/node_index.html'
    context = {}
    context['nodes'] = BLOCKCHAIN.nodes
    return render(request, template, context)

def consensus(request):
    template = 'chain/nodes_resolve.html'
    context = {}
    replaced = BLOCKCHAIN.resolve_conflicts()

    if replaced:
        msg = 'Our chain was replaced'
        context['msg'] = msg
        context['chain'] = BLOCKCHAIN.chain
        messages.error(request, msg)
    else:
        msg = 'Our chain was preferred'
        context['msg'] = msg
        context['chain'] = BLOCKCHAIN.chain
        messages.success(request, msg)
    # return redirect('blockchain:node_index')
    return render(request, template, context)

chain/templates/chain/block_detail.html
{% extends "voidcoin_base.html" %}
{% block title %}Block number {{ number }}{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% load chain_templatetags %}

{% block content_content %}

<h1>Block number {{ number }}</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Blocks</a></li>
        <li class="breadcrumb-item active">Block number {{ number }}</li>
    </ol>
</nav>


{% for key, value in block_items.items %}

    {% if key == 'transactions' %}
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                    <caption>Transactions in block number {{ number }}</caption>
                    <tr>
                        <th>S/No.</th>
                        <th>Amount</th>
                        <th>Sender</th>
                        <th>Recipient</th>
                    </tr>
                </thead>
                <tbody>

                {% for transaction in value %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ transaction.amount }}</td>
                        <td title="{{ transaction.sender_address }}">{{ transaction.sender_address|truncatechars:10 }}</td>
                        <td title="{{ transaction.recipient_address }}">{{ transaction.recipient_address|truncatechars:10 }}</td>
                    </tr>
                {% empty %}
                    <p>No transaction in block</p>
                {% endfor %}
                <tr>
                    <td>Sum</td>
                    <td>{{ value|sum_amounts }}</td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    {% else %}
        <h6 style="word-break:break-all">{{ key }}: {{ value }}</h6>
    {% endif %}
{% endfor %}

{% endblock content_content %}

chain/templates/chain/edit_alias.html
{% extends "voidcoin_base.html" %}
{% block title %}Edit account alias{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}
<div class="container upload-forms">
    <h2>Edit account alias</h2>
    <hr>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Send">Send</button>
    </form>
</div>
{% endblock content_content %}

chain/templates/chain/edit_identify.html
{% extends "voidcoin_base.html" %}
{% block title %}Edit account identifier{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}
<div class="container upload-forms">
    <h2>Edit account identifier</h2>
    <hr>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Send">Send</button>
    </form>
</div>
{% endblock content_content %}

chain/templates/chain/generate_transaction.html
{% extends "blockchain_base.html" %}
{% block title %}Generate new transaction{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}
<div class="container upload-forms">
    <h2>Generate new transaction</h2>
    <hr>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Send">Send</button>
    </form>
</div>
{% endblock content_content %}

chain/templates/chain/index.html
{% extends "voidcoin_base.html" %}
{% block title %}Home{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}
<h1>VoidCoin</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
    </ol>
</nav>

<h2>Block constraints</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Block constraints</caption>
            <tr>
                <th>S/No.</th>
                <th>Constraint</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Coin base</td>
                <td>{{ coin_base }}</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Remaining</td>
                <td>{{ unassigned }}</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Mining reward</td>
                <td>{{ mining_reward }}</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Mining difficulty</td>
                <td>{{ mining_difficulty }}</td>
            </tr>
            <tr>
                <td>5</td>
                <td>Mineable transaction length</td>
                <td>{{ mineable }}</td>
            </tr>
        </tbody>
    </table>
</div>

<hr>

<h2>Transactions for next block</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Next block transactions</caption>
            <tr>
                <th>S/No.</th>
                <th>Amount</th>
                <th>Sender</th>
                <th>Recipient</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in pending_transactions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ transaction.amount }}</td>
                <td title="{{ transaction.sender_address }}">{{ transaction.sender_address|truncatechars:10 }}</td>
                <td title="{{ transaction.recipient_address }}">{{ transaction.recipient_address|truncatechars:10 }}</td>
            </tr>
        {% empty %}
            <p>No pending transaction</p>
        {% endfor %}
        </tbody>
    </table>
</div>

<hr>

<h2>Blocks on the chain</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Blocks</caption>
            <tr>
                <th>Number</th>
                <th>nonce</th>
                <th>Previous hash</th>
                <th>Timestamp</th>
                <th>Transactions</th>
            </tr>
        </thead>
        <tbody>
        {% for block in chain %}
            <tr>
                {% for key, value in block.items %}
                    {% if key == 'transactions' %}
                        <td title="{{ value }}">{{ value|truncatechars:10 }}</td>
                    {% elif key == 'number' %}
                        <td><a href="{% url 'blockchain:block_detail' value %}">{{ value }}</a></td>
                    {% else %}
                        <td>{{ value }}</td>
                    {% endif %}

                {% endfor %}
            </tr>
        {% empty %}
            <p>No blocks on the chain</p>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content_content %}

chain/templates/chain/initiate_transaction.html
{% extends "voidcoin_base.html" %}
{% block title %}New transaction{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>New transaction</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">New transaction</li>
    </ol>
</nav>

<div class="container upload-forms">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Send">Send</button>
    </form>
</div>
{% endblock content_content %}

chain/templates/chain/mine.html
{% extends "voidcoin_base.html" %}
{% block title %}Chain object{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% load static %}

{% block content_content %}

<h1>Chain object</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">Chain object</li>
    </ol>
</nav>

{{ blockchain }}

{% endblock content_content %}

chain/templates/chain/node_index.html
{% extends "voidcoin_base.html" %}
{% block title %}Nodes{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Nodes</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">Nodes</li>
    </ol>
</nav>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Nodes</caption>
            <tr>
                <th>S/No.</th>
                <th>Node</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tbody>
        {% for key, value in nodes.items %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
        {% empty %}
            <p>No nodes</p>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content_content %}
{% block footer %}{% endblock footer %}

chain/templates/chain/node_register.html
{% extends "voidcoin_base.html" %}
{% block title %}Register nodes{% endblock %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}

<h1>Register nodes</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Nodes</a></li>
        <li class="breadcrumb-item active">Register nodes</li>
    </ol>
</nav>
<div class="container upload-forms">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm float-right" type="submit" value="Register">Register</button>
    </form>
</div>
{% endblock content_content %}

chain/templates/chain/nodes_resolve.html
{% extends "voidcoin_base.html" %}
{% block title %}Resolve nodes{% endblock title %}
{% block introduction %}{% endblock introduction %}

{% block content_content %}


<h1>Resolve nodes</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Nodes</a></li>
        <li class="breadcrumb-item active">Resolve nodes</li>
    </ol>
</nav>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Nodes</caption>
            <tr>
                <th>S/No.</th>
                <th>Node</th>
            </tr>
        </thead>
        <tbody>
        {% for node in nodes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ node }}</td>
            </tr>
        {% empty %}
            <p>No nodes</p>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content_content %}
{% block footer %}{% endblock footer %}

chain/templates/chain/transactions_destined_for_next_block.html
{% extends "voidcoin_base.html" %}
{% block title %}Transactions for next block{% endblock title %}
{% load chain_templatetags %}

{% block content_content %}

<h1>Transactions for next block</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/">Transactions</a></li>
        <li class="breadcrumb-item active">Transactions for next block</li>
    </ol>
</nav>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Transactions for next block</caption>
            <tr>
                <th>S/No.</th>
                <th>Amount</th>
                <th>Timestamp</th>
                <th>Sender</th>
                <th>Recipient</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.timestamp }}</td>
                <td title="{{ transaction.sender_address }}">{{ transaction.sender_address|truncatechars:10 }}</td>
                <td title="{{ transaction.recipient_address }}">{{ transaction.recipient_address|truncatechars:10 }}</td>
            </tr>
        {% empty %}
            <p>No pending transactions</p>
        {% endfor %}
        <tr>
            <td>Sum</td>
            <td>{{ transactions|sum_amounts }}</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
    </table>
</div>

{% endblock content_content %}
{% block footer %}{% endblock footer %}

chain/templates/chain/transactions_in_block.html
{% extends "blockchain_base.html" %}
{% block title %}Transactions in block{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% load static %}

{% block content_content %}

{{ transactions }}

{% endblock content_content %}

chain/templates/chain/transactions_index.html
{% extends "voidcoin_base.html" %}
{% block title %}Transactions{% endblock title %}
{% block introduction %}{% endblock introduction %}
{% load chain_templatetags %}

{% block content_content %}

<h1>Transactions on the blockchain</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active">Transactions on the blockchain</li>
    </ol>
</nav>

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <caption>Transactions on the blockchain</caption>
            <tr>
                <th>S/No.</th>
                <th>Amount</th>
                <th>Sender</th>
                <th>Recipient</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}

            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ transaction.amount }}</td>
                <td title="{{ transaction.sender_address }}">{{ transaction.sender_address|truncatechars:10 }}</td>
                <td title="{{ transaction.recipient_address }}">{{ transaction.recipient_address|truncatechars:10 }}</td>
            </tr>
        {% empty %}
            <p>No transactions made yet</p>
        {% endfor %}
        <tr>
            <td>Sum</td>
            <td>{{ transactions|sum_amounts }}</td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
    </table>
</div>

{% endblock content_content %}
{% block footer %}{% endblock footer %}